### PR TITLE
Script to generate files for a new rule

### PR DESCRIPTION
**Pull request by JKillian**
Wrote a script to generate files for a new rule automatically, figured it was worth sharing. It's in Ruby because Ruby is fun! 💎 

Figured if it's useful we could consider moving it over to actual TSLint eventually

### CODE REVIEW

**Comment by adidahiya** [comment]
Although Ruby is fun, I think this script is pretty easy to port to node.js. Let's try to avoid introducing additional dev dependencies.

**Comment by JKillian** [comment]
Would we write it in JS or TS though?

**Comment by adidahiya** [comment]
ES2015 JS for node v5+ is fine, especially since we only have one script right now

**Comment by JKillian** [comment]
Modern JS is surprisingly usable, the actual changes between Ruby and JS are pretty palatable. JS's stdlib is a little lacking though, strings and array could use a few more build-in methods in my opinion

**Pull request merged**
