### PR TITLE
Upgrade TSLint & TypeScript, disable formatting rules

### PR DESCRIPTION
**Pull request by adidahiya**

### CODE REVIEW

**Comment by SaeedZhiany** [comment]
@adidahiya 

I'm wondering why the formatting rules have been disabled? are all they covered by [tslint](https://github.com/palantir/tslint)?

**Comment by SaeedZhiany** [comment]
@adidahiya 

I'm wondering why the formatting rules have been disabled? are all they covered by [tslint](https://github.com/palantir/tslint)?

is it safe to upgrade my project tslint and tslint-react to 6.1.2 and 5.0.0, respectively? (I know we should migrate to eslint and prettier, but I still want to use them until I found some free times to migration)

Thanks

**Comment by SaeedZhiany** [comment]
@adidahiya 

I'm wondering why the formatting rules have been disabled? are all they covered by [tslint](https://github.com/palantir/tslint)?

is it safe to upgrade my project tslint and tslint-react to 6.1.2 and 5.0.0, respectively (I'm currently using tslint 6.1.1 and tslint 4.2.0)? (I know we should migrate to eslint and prettier, but I still want to use them until I found some free times to migration)

Thanks

**Comment by adidahiya** [comment]
They're removed because we recommend using prettier. You don't have to migrate to eslint to do this, it's pretty easy with tslint-plugin-prettier. The change to remove formatting rules from tslint and tslint-react obviates tslint-config-prettier. Related PR: https://github.com/palantir/tslint/pull/4871

**Pull request merged**
