### PR TITLE
Mwong/block build on test failure

### LINKED ISSUE #42: Tests are failing on master
Seems like test failure doesn't block build:

https://circleci.com/gh/palantir/tslint-react/76#tests/containers/0

### PR DESCRIPTION
**Pull request by markwongsk**
Fixes #42

### CODE REVIEW

**Comment by adidahiya** [comment]
Can you enable Circle CI on your fork so we can verify this before merging?

**Comment by markwongsk** [comment]
Done. Sorry about forgetting to turn it on.

**Comment by markwongsk** [comment]
Seems like `ls **` didn't do what I thought it would do. This currently doesn't run the `jsx-curly-spacing` tests, and I have a fix for it in my PR here: https://github.com/palantir/tslint-react/pull/49/commits/af77fcfccb1fcc0e3780ec9ed002499f66dd9082#diff-3599146d921f1027fdc9ea471fc82a56R4. LMK if you want me to open this as a separate PR, or if you're fine with just merging it with that PR.

**Comment by adidahiya** [comment]
fine to do in that PR

**Pull request merged**
