### PR TITLE
Update to tslint 4.0.1 and TypeScript 2.0.10

### PR DESCRIPTION
**Pull request by tiagoefmoraes**
Fixed some new issues with tslint --fix and raised max-classes-per-file to 2

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint-react](https://github.com/palantir/tslint-react), @tiagoefmoraes! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by adidahiya** [comment]
@nchen63 can you please take a look

**Comment by nchen63** [comment]
@adidahiya looks good to me

**Comment by adidahiya** [comment]
thanks @tiagoefmoraes!

**Pull request merged**
