### PR TITLE
Explicit peer dependencies

### LINKED ISSUE #106: Missing dependencies after installation with npm@5.2
After installation of `tslint-react` with npm v5.2.0 I got a
```
Warning: Cannot find module 'tsutils' Use --force to continue.
```
After digging through the sources I found that rules implementations (i.e. `tslint-react/rules/jsxAlignmentRule.js`) require node modules `tslint`, `typescript` and `tslint` but not any of these modules is listed in `dependencies` or `peerDependencies`.

### PR DESCRIPTION
**Pull request by adidahiya**
Fixes #106

### CODE REVIEW

**Comment by timocov** [comment]
@adidahiya why `tsutils` is `peerDependencies` instead of just `dependencies`?

**Comment by timocov** [comment]
I guess it is similar to https://github.com/Microsoft/tslint-microsoft-contrib/pull/371.

We have an error `Error: Cannot find module 'tsutils'` after run tslint

**Comment by adidahiya** [comment]
Meh, this is kind of the reason I never listed explicit peer dependencies in the first place (it gets tedious to maintain and doesn't provide many benefits). The whole idea here is to prevent multiple versions of `tsc` from being used in TSLint and its rule implementations at runtime. If I make `tsutils` a regular `dependency` then I believe there's a possibility that NPM could install a nested `typescript` module inside `tsutils/node_modules` and now we have two versions in use at runtime (despite the fact that `typescript` itself is a peer dependency of `tslint-react`) -- I'll need to double-check this.

**Comment by timocov** [comment]
I agree, it is good reason. But `typescript` is a peer dependency of `tsutils` (https://github.com/ajafff/tsutils/blob/master/package.json#L43) and I guess that if you use that library with specific API for specific range of versions you should make it as dependency.

**Comment by timocov** [comment]
And now with `npm@5.2.0` we have an error about not-installed `tsutils` for `tslint-react` (yeah, it is bug of `npm` but I guess `package.json` of `tslint-react` should has `tsulits` as deps)

**Comment by adidahiya** [comment]
@ajafff do you have any opinions here?

**Comment by ajafff** [comment]
As @timocov said, tsutils has typescript in peerDependencies. Hence there will only be one version of typescript installed. 

The only reason to put tsutils in peerDependencies is to avoid different (major)  versions of it in tslint and rules packages. But I don't think that's necessary.

**Comment by adidahiya** [comment]
@ajafff given that logic, it should probably be safe to make `tslint` also a regular dependency then? Since it also declares `typescript` as a peer.

**Comment by timocov** [comment]
I think that `tslint` should be peer dependency because `tslint-react` is plugin for `tslint`. Yes, `tslint-react` depends on `tslint` but in development only and just for typings.

**Comment by ajafff** [comment]
I agree with @timocov. A plugin should not bring it's own version of the library it plugs into.

Take `vrsource-tslint-rules` for example: It has a [regular dependency on `tslint@^4.1.1`](https://github.com/vrsource/vrsource-tslint-rules/blob/master/package.json#L23). You can install this package even if you have `tslint@^5.0.0` installed. You won't notice any incompatibility until you experience a runtime crash.

**Pull request merged**
