### PR TITLE
Add jsx-space-before-trailing-slash rule

### LINKED ISSUE #125: New rule: jsx-space-before-trailing-slash
Prefer `<MyComponent />` than `<MyComponent/>`

[XHTML species](https://www.w3.org/TR/xhtml1/#C_2):

> ## C.2. Empty Elements
>
> Include a space before the trailing `/` and `>` of empty elements, e.g. `<br />`, `<hr />` and `Karen`. Also, use the minimized tag syntax for empty elements, e.g. `<br />`, as the alternative syntax `<br></br>` allowed by XML gives uncertain results in many existing user agents.

### PR DESCRIPTION
**Pull request by no23reason**
Closes #125

### CODE REVIEW

**Comment by suchanlee** [comment]
Thanks for the PR! Looks awesome. I will look into the build issue, probably sometime this weekend or early next week.

**Comment by JKillian** [comment]
Hey @no23reason, I was able to get your PR build working over at https://github.com/palantir/tslint-react/pull/164, it's merged now! Going to close this one out then

**Comment by evaliyev** [comment]
@suchanlee I was wondering why this rule was implemented as turn on/off rule? 
That is, instead of having options ` true/false` that enforces or disables adding spaces, you could have options `["always", "never"]` that give more control and can enforce both addition and removal on spaces.

**Comment by no23reason** [comment]
@evaliyev I believe the original intent of this rule was to enforce the presence of the space, not its absence. However, if there really are projects that want to explicitly remove the space (I have never encountered one), this rule should be easy to extend.

**Pull request closed without merging**
