### PR TITLE
Add options to allow HTML entities and/or punctuation to be excluded from translation check

### PR DESCRIPTION
**Pull request by praxxis**
This will allow, for example, `&nbsp;` to be the contents of an element.

This also unifies the way "text" is checked for across all types of elements/attributes.

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint-react](https://github.com/palantir/tslint-react), @praxxis! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

**Comment by praxxis** [comment]
fixes #119

**Comment by adidahiya** [comment]
@praxxis can you enable CI for your fork please? https://circleci.com/projects

**Comment by praxxis** [comment]
@adidahiya I've enabled CI and it's passing

**Comment by praxxis** [comment]
@adidahiya is anything else I need to do to get this merged?

**Comment by jamtur01** [comment]
@adidahiya we'd love to see this merged as its blocking a couple of things! Thanks muchly. 👍 💚

**Pull request merged**
