### PR TITLE
Implement jsx-key rule

### PR DESCRIPTION
**Pull request by bolatovumar**
Issue #101

### CODE REVIEW

**Comment by bolatovumar** [comment]
@adidahiya looks like something is wrong with circleci?

**Comment by adidahiya** [comment]
@bolatovumar have you enabled Circle on your fork? you have to log in and click "Build project" on your fork.

**Comment by adidahiya** [comment]
ping @bolatovumar

**Comment by bolatovumar** [comment]
@adidahiya seems like i was able to trigger CircleCI this time and all went well

**Comment by adidahiya** [comment]
thanks @bolatovumar

**Pull request merged**
